#!/usr/bin/env bash

# Assumes that your ssh config is set up with github as the name of an entry to
# login to github.com as the user git. Takes an SSH URL as copied from
# github.com and clones it, such that git instead uses the github entry in your
# ssh config to clone it, so that it uses any ssh identities set up in your
# ~/.ssh/config for interacting with github.com.

# Following [this stackoverflow
# post](https://stackoverflow.com/questions/3811345/how-to-pass-all-arguments-passed-to-my-bash-script-to-a-function-of-mine)
# for a bash-y way to extract the rest of the arguments
git clone $(echo $1 | awk -F: '{print "github:" $2}') "${@:2}"
